# Generated by Django 6.0.5 on 2026-09-30 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. 2026-2027', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('first_friday_june', models.DateField(help_text='DepEd cut-off date for baseline enrollment')),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(default='Standard Faculty Shift', max_length=100)),
                ('regular_days_label', models.CharField(default='8:00 to 12:00 and 1:00 to 5:00', max_length=100)),
                ('saturday_label', models.CharField(blank=True, default='', max_length=100)),
                ('am_arrival_start', models.TimeField(default='06:30:00')),
                ('am_arrival_cutoff', models.TimeField(default='07:45:00', help_text='Arrival past this is marked Late')),
                ('am_departure_time', models.TimeField(default='12:00:00')),
                ('pm_arrival_time', models.TimeField(default='13:00:00')),
                ('pm_departure_cutoff', models.TimeField(default='17:00:00', help_text='Departure before this is Undertime')),
                ('late_threshold_min', models.IntegerField(default=15, help_text='Grace period for classroom scans')),
            ],
            options={
                'db_table': 'class_schedules',
            },
        ),
        migrations.CreateModel(
            name='GeofenceSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Campus Boundary', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'geofence_settings',
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. G7, G11', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School'), ('ALS', 'Alternative Learning System')], default='JHS', max_length=10)),
                ('level_order', models.IntegerField(default=7)),
            ],
            options={
                'db_table': 'grade_levels',
                'ordering': ['level_order'],
            },
        ),
        migrations.CreateModel(
            name='IoTKiosk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kiosk_code', models.CharField(help_text='e.g. KIOSK-MAIN-GATE', max_length=50, unique=True)),
                ('terminal_name', models.CharField(max_length=150)),
                ('secret_hash', models.CharField(help_text='Hardware authentication key', max_length=255)),
                ('location', models.CharField(default='Main Gate', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'iot_kiosks',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('position', models.CharField(default='Teacher I', max_length=100)),
                ('department', models.CharField(default='Junior High School', max_length=100)),
                ('contact_number', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('photo', models.ImageField(blank=True, default='staff/default_avatar.png', upload_to='staff/')),
                ('rfid_uid', models.CharField(help_text='Unique RFID card serial number', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'staff_profiles',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. MATH7, ENG10', max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('tier', models.CharField(default='JHS', max_length=10)),
                ('subject_type', models.CharField(default='CORE', max_length=20)),
                ('units', models.IntegerField(default=4)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Diamond, Emerald', max_length=100)),
                ('track_strand', models.CharField(blank=True, default='', max_length=150)),
                ('room_number', models.CharField(default='Room 101', max_length=50)),
                ('capacity', models.IntegerField(default=40)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.academicyear')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.gradelevel')),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advising_sections', to='academics.staffprofile')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['name'],
                'unique_together': {('academic_year', 'grade_level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SmsOutbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipient_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('trigger_event', models.CharField(default='CLASS_TAP', max_length=50)),
                ('priority', models.SmallIntegerField(default=2, help_text='1=Urgent, 2=Standard')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sms_outbox',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='idx_sms_queue_fetch')],
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_id', models.CharField(help_text='DepEd 6-digit School ID', max_length=50, unique=True)),
                ('school_name', models.CharField(default='Lapasan National High School', max_length=255)),
                ('region', models.CharField(default='Region X', max_length=50)),
                ('division', models.CharField(default='Cagayan de Oro City', max_length=150)),
                ('district', models.CharField(default='District II', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, default='schools/default_logo.png', upload_to='schools/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='academics.academicyear')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_schools', to='academics.staffprofile')),
            ],
            options={
                'db_table': 'school_profile',
            },
        ),
        migrations.CreateModel(
            name='LoafingIncident',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incident_date', models.DateField(default=django.utils.timezone.now)),
                ('trigger_reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('EXCUSED', 'Excused'), ('CONFIRMED', 'Confirmed Violation')], default='PENDING_REVIEW', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loafing_logs', to='academics.staffprofile')),
            ],
            options={
                'db_table': 'loafing_incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lrn', models.CharField(help_text='12-digit DepEd LRN', max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birthdate', models.DateField(help_text='Calculates Age on October 31 for SF1')),
                ('mother_tongue', models.CharField(blank=True, default='Cebuano', max_length=100)),
                ('ethnic_group', models.CharField(blank=True, default='', max_length=100)),
                ('religion', models.CharField(blank=True, default='Roman Catholic', max_length=100)),
                ('house_street_sitio', models.CharField(blank=True, default='', max_length=255)),
                ('barangay', models.CharField(blank=True, default='Lapasan', max_length=100)),
                ('municipality_city', models.CharField(blank=True, default='Cagayan de Oro City', max_length=100)),
                ('province', models.CharField(blank=True, default='Misamis Oriental', max_length=100)),
                ('father_name', models.CharField(blank=True, default='', max_length=200)),
                ('mother_maiden_name', models.CharField(blank=True, default='', max_length=200)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, default='', max_length=50)),
                ('parent_contact', models.CharField(help_text='Parent mobile phone for SMS', max_length=50)),
                ('photo', models.ImageField(blank=True, default='students/default_avatar.png', upload_to='students/')),
                ('qr_token', models.CharField(help_text='Printed QR code on PVC card', max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['lrn'], name='idx_student_lrn'), models.Index(fields=['qr_token'], name='idx_student_qr')],
            },
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pass_number', models.CharField(max_length=50, unique=True)),
                ('pass_type', models.CharField(default='OFFICIAL_BUSINESS', max_length=50)),
                ('reason', models.TextField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_passes', to='academics.staffprofile')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.staffprofile')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.student')),
            ],
            options={
                'db_table': 'gate_passes',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(default='Room 101', max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.section')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to='academics.staffprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.subject')),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('REGISTRAR', 'Registrar'), ('TEACHER', 'Teacher')], default='TEACHER', max_length=20)),
                ('avatar', models.ImageField(blank=True, default='avatars/default_user.png', upload_to='avatars/')),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='academics.staffprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat, 7=Sun')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='academics.schedule')),
            ],
            options={
                'db_table': 'schedule_days',
                'unique_together': {('schedule', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='StaffGateLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=10)),
                ('card_uid', models.CharField(max_length=64)),
                ('kiosk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.iotkiosk')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_logs', to='academics.staffprofile')),
            ],
            options={
                'db_table': 'staff_gate_logs',
                'ordering': ['-scan_time'],
                'indexes': [models.Index(fields=['staff', 'scan_time'], name='idx_staff_scan_time')],
            },
        ),
        migrations.CreateModel(
            name='FacultyHeartbeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('battery_level', models.IntegerField(default=100)),
                ('is_inside_geofence', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='academics.staffprofile')),
            ],
            options={
                'db_table': 'faculty_heartbeats',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['staff', 'recorded_at'], name='idx_heartbeat_time')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('enrollment_type', models.CharField(default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped Out'), ('TRANSFERRED_IN', 'Transferred In'), ('TRANSFERRED_OUT', 'Transferred Out')], default='ENROLLED', max_length=20)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('status_reason_code', models.CharField(blank=True, default='', help_text='e.g. a.1, b.1 on SF2', max_length=20)),
                ('transferred_school', models.CharField(blank=True, default='', max_length=255)),
                ('is_cct_recipient', models.BooleanField(default=False, help_text='4Ps / CCT recipient flag')),
                ('cct_id_number', models.CharField(blank=True, default='', max_length=50)),
                ('disability_detail', models.CharField(blank=True, default='', max_length=150)),
                ('accelerated_detail', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.student')),
            ],
            options={
                'db_table': 'enrollments',
                'indexes': [models.Index(fields=['academic_year', 'section', 'status'], name='idx_enroll_summary')],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PRESENT', max_length=10)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='academics.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='academics.student')),
            ],
            options={
                'db_table': 'daily_attendance_summaries',
                'indexes': [models.Index(fields=['section', 'attendance_date'], name='idx_daily_sec_date')],
                'unique_together': {('student', 'attendance_date')},
            },
        ),
        migrations.CreateModel(
            name='SubjectAttendanceLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField(default=django.utils.timezone.now)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('CUTTING', 'Cutting Classes'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendance', to='academics.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_attendance', to='academics.staffprofile')),
            ],
            options={
                'db_table': 'subject_attendance_logs',
                'indexes': [models.Index(fields=['attendance_date', 'schedule', 'status'], name='idx_sub_att_lookup')],
                'unique_together': {('student', 'schedule', 'attendance_date')},
            },
        ),
    ]
