# Generated by Django 6.0.5 on 2026-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='label',
            field=models.CharField(choices=[('Regular Faculty Shift', 'Regular Faculty Shift (7:45 AM - 5:00 PM)'), ('Senior High Shift', 'Senior High School Shift (7:30 AM - 4:30 PM)'), ('Night High School Shift', 'Night High School Shift (1:00 PM - 9:00 PM)'), ('ALS Field Shift', 'ALS Field Coordinator Shift (Flexible 8 Hours)')], default='Regular Faculty Shift', max_length=100),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='regular_days_label',
            field=models.CharField(choices=[('8:00 to 12:00 and 1:00 to 5:00', '8:00 to 12:00 and 1:00 to 5:00 (DepEd CSC 48 Standard)'), ('7:30 to 11:30 and 12:30 to 4:30', '7:30 to 11:30 and 12:30 to 4:30'), ('6:00 to 12:00 and 12:30 to 2:30', '6:00 to 12:00 (Double Shift - AM)'), ('12:00 to 6:00 (Afternoon Shift)', '12:00 to 6:00 (Double Shift - PM)')], default='8:00 to 12:00 and 1:00 to 5:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyattendancesummary',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late / Tardy'), ('CUTTING', 'Cutting Classes'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Enrollee'), ('LATE_ENROLLEE', 'Late Enrollee (After First Friday of June)'), ('TRANSFERRED_IN', 'Transferred In from Other School'), ('BALIK_ARAL', 'Balik-Aral (Returning Learner)'), ('REPEATER', 'Repeater / Retained')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status_reason_code',
            field=models.CharField(blank=True, choices=[('', 'None / Not Applicable'), ('a.1', 'a.1 Academic: Difficulty in School Work'), ('a.2', 'a.2 Academic: Lack of Personal Interest'), ('b.1', 'b.1 Individual: Severe Illness / Disability'), ('b.2', 'b.2 Individual: Teenage Pregnancy / Early Marriage'), ('b.3', 'b.3 Individual: Substance / Behavioral Issue'), ('c.1', 'c.1 Family: Poverty / Financial Constraints'), ('c.2', 'c.2 Family: Need to Work / Assist Family Livelihood'), ('c.3', 'c.3 Family: Domestic Problems / Family Relocation'), ('d.1', 'd.1 Community: Extreme Distance / No Transport'), ('d.2', 'd.2 Community: Armed Conflict / Calamity'), ('e.1', 'e.1 Other Unclassified Factor')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='pass_type',
            field=models.CharField(choices=[('OFFICIAL_BUSINESS', 'Official Business (OB)'), ('MEDICAL_EMERGENCY', 'Medical Emergency / Clinic Referral'), ('EARLY_DISMISSAL', 'Authorized Early Dismissal'), ('PERSONAL_MATTER', 'Approved Personal Urgent Matter')], default='OFFICIAL_BUSINESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Ready to Use'), ('USED', 'Used / Checked at Gate'), ('EXPIRED', 'Expired Validity'), ('REVOKED', 'Revoked / Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='geofencesetting',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=8.4862, max_digits=9),
        ),
        migrations.AlterField(
            model_name='geofencesetting',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=124.6618, max_digits=9),
        ),
        migrations.AlterField(
            model_name='iotkiosk',
            name='location',
            field=models.CharField(choices=[('Main Entrance Gate', 'Main Campus Entrance Gate (Terminal 1)'), ('Main Exit Gate', 'Main Campus Exit Gate (Terminal 2)'), ('Back Gate', 'Back Secondary Gate'), ('Senior High School Gate', 'Senior High School Building Gate'), ('Faculty Center Entrance', 'Faculty Administration Lobby')], default='Main Entrance Gate', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleday',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='address',
            field=models.TextField(blank=True, default='Lapasan, Cagayan de Oro City, Misamis Oriental'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(choices=[('District I', 'District I (North/West CDO)'), ('District II', 'District II (East CDO - Lapasan / Gusa / Cugman)'), ('District III', 'District III'), ('District IV', 'District IV'), ('District V', 'District V'), ('District VI', 'District VI')], default='District II', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='division',
            field=models.CharField(choices=[('Cagayan de Oro City', 'Division of Cagayan de Oro City'), ('Misamis Oriental', 'Division of Misamis Oriental'), ('Bukidnon', 'Division of Bukidnon'), ('Iligan City', 'Division of Iligan City'), ('Gingoog City', 'Division of Gingoog City'), ('El Salvador City', 'Division of El Salvador City')], default='Cagayan de Oro City', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='region',
            field=models.CharField(choices=[('Region X', 'Region X - Northern Mindanao'), ('Region XIII', 'Region XIII - Caraga'), ('Region IX', 'Region IX - Zamboanga Peninsula'), ('Region XI', 'Region XI - Davao Region'), ('Region XII', 'Region XII - SOCCSKSARGEN'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao'), ('NCR', 'National Capital Region')], default='Region X', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='room_number',
            field=models.CharField(choices=[('Room 101', 'Room 101 - Ground Floor'), ('Room 102', 'Room 102 - Ground Floor'), ('Room 201', 'Room 201 - Second Floor'), ('Room 202', 'Room 202 - Second Floor'), ('Room 301', 'Room 301 - Third Floor'), ('Room 302', 'Room 302 - Third Floor'), ('Science Lab', 'Science Laboratory'), ('Computer Lab', 'Computer Laboratory'), ('Gymnasium', 'School Gymnasium')], default='Room 101', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='track_strand',
            field=models.CharField(blank=True, choices=[('', 'N/A (Junior High School)'), ('STEM', 'STEM - Science, Technology, Engineering and Mathematics'), ('ABM', 'ABM - Accountancy, Business and Management'), ('HUMSS', 'HUMSS - Humanities and Social Sciences'), ('GAS', 'GAS - General Academic Strand'), ('TVL-ICT', 'TVL - Information & Communications Technology'), ('TVL-HE', 'TVL - Home Economics'), ('TVL-IA', 'TVL - Industrial Arts'), ('TVL-AFA', 'TVL - Agri-Fishery Arts'), ('Sports', 'Sports Track'), ('Arts & Design', 'Arts & Design Track')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'Priority 1 - Urgent (Absence, Cutting, Gate Violation)'), (2, 'Priority 2 - Standard (Regular Present Tap)')], default=2),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Transmission'), ('PROCESSING', 'Processing by Serial Modem'), ('SENT', 'Sent / Delivered'), ('FAILED', 'Failed / Exhausted Retries')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='trigger_event',
            field=models.CharField(choices=[('CLASS_TAP', 'Classroom Attendance Tap'), ('GATE_TAP', 'Gate Kiosk RFID Tap'), ('GATE_PASS', 'Gate Pass Issuance'), ('LOAFING_ALERT', 'Campus Perimeter Breach Alert'), ('SARDO_WARNING', 'SARDO (5-Day Consecutive Absence) Alert'), ('MANUAL_ANNOUNCEMENT', 'Institutional School Broadcast')], default='CLASS_TAP', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffgatelog',
            name='direction',
            field=models.CharField(choices=[('IN', 'Time In (Arrival)'), ('OUT', 'Time Out (Departure)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('Junior High School', 'Junior High School Faculty'), ('Senior High School', 'Senior High School Faculty'), ('Alternative Learning System (ALS)', 'ALS Department'), ('Science Department', 'Science Department'), ('Mathematics Department', 'Mathematics Department'), ('English Department', 'English Department'), ('Filipino Department', 'Filipino Department'), ('Social Studies (AP) Department', 'Araling Panlipunan Department'), ('MAPEH Department', 'MAPEH Department'), ('TLE / TVL Department', 'TLE / TVL Department'), ('Values Education (EsP) Department', 'Edukasyon sa Pagpapakatao Department'), ('Administration & Registrar', 'Administrative & Registrar Office')], default='Junior High School', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('Teacher I', 'Teacher I'), ('Teacher II', 'Teacher II'), ('Teacher III', 'Teacher III'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher II', 'Master Teacher II'), ('Head Teacher I', 'Head Teacher I'), ('Head Teacher II', 'Head Teacher II'), ('Head Teacher III', 'Head Teacher III'), ('Secondary School Principal I', 'Secondary School Principal I'), ('Secondary School Principal II', 'Secondary School Principal II'), ('Secondary School Principal III', 'Secondary School Principal III'), ('Secondary School Principal IV', 'Secondary School Principal IV'), ('Administrative Officer II', 'Administrative Officer II'), ('Administrative Assistant II', 'Administrative Assistant II'), ('Registrar I', 'Registrar I')], default='Teacher I', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='suffix',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='barangay',
            field=models.CharField(choices=[('Lapasan', 'Lapasan'), ('Gusa', 'Gusa'), ('Cugman', 'Cugman'), ('Tablon', 'Tablon'), ('Puerto', 'Puerto'), ('Bugo', 'Bugo'), ('Macabalan', 'Macabalan'), ('Puntod', 'Puntod'), ('Consolacion', 'Consolacion'), ('Camaman-an', 'Camaman-an'), ('Nazareth', 'Nazareth'), ('Carmen', 'Carmen'), ('Kauswagan', 'Kauswagan'), ('Bulua', 'Bulua'), ('Patag', 'Patag'), ('Iponan', 'Iponan'), ('Lumbia', 'Lumbia'), ('Balulang', 'Balulang'), ('Canitoan', 'Canitoan'), ('Barangay 1', 'Poblacion - Barangay 1'), ('Barangay 2', 'Poblacion - Barangay 2'), ('Barangay 10', 'Poblacion - Barangay 10'), ('Other', 'Other Barangay (Outside CDO)')], default='Lapasan', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Elder Sister', 'Elder Sister'), ('Elder Brother', 'Elder Brother'), ('Legal Guardian', 'Court-Appointed Legal Guardian'), ('Other', 'Other Custodian')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(choices=[('Cebuano', 'Cebuano / Bisaya'), ('Tagalog', 'Tagalog / Filipino'), ('Maranao', 'Maranao'), ('Hiligaynon', 'Hiligaynon / Ilonggo'), ('Binukid', 'Binukid'), ('Subanen', 'Subanen'), ('Waray', 'Waray'), ('Ilocano', 'Ilocano'), ('English', 'English'), ('Other', 'Other Indigenous Language')], default='Cebuano', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='municipality_city',
            field=models.CharField(choices=[('Cagayan de Oro City', 'Cagayan de Oro City'), ('Tagoloan', 'Tagoloan'), ('Villanueva', 'Villanueva'), ('Jasaan', 'Jasaan'), ('Opol', 'Opol'), ('El Salvador City', 'El Salvador City'), ('Claveria', 'Claveria'), ('Other', 'Other Municipality/City')], default='Cagayan de Oro City', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(choices=[('Misamis Oriental', 'Misamis Oriental'), ('Bukidnon', 'Bukidnon'), ('Lanao del Norte', 'Lanao del Norte'), ('Misamis Occidental', 'Misamis Occidental'), ('Camiguin', 'Camiguin'), ('Other', 'Other Province')], default='Misamis Oriental', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Roman Catholic', 'Roman Catholic'), ('Islam', 'Islam'), ('Seventh-day Adventist', 'Seventh-day Adventist'), ('Iglesia ni Cristo', 'Iglesia ni Cristo'), ('Evangelical Christian', 'Evangelical Christian'), ('Baptist', 'Baptist'), ('Born Again Christian', 'Born Again Christian'), ("Jehovah's Witnesses", "Jehovah's Witnesses"), ('UCCP', 'United Church of Christ in the Philippines (UCCP)'), ('IFI / Aglipayan', 'Iglesia Filipina Independiente (IFI)'), ('Other', 'Other Religious Affiliation')], default='Roman Catholic', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='suffix',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('CORE', 'Core Curriculum Subject'), ('APPLIED', 'Applied Track Subject'), ('SPECIALIZED', 'Specialized Strand Subject'), ('ALS_MODULE', 'ALS Learning Strand Module')], default='CORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tier',
            field=models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School'), ('ALS', 'Alternative Learning System')], default='JHS', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.IntegerField(choices=[(1, '1 Unit'), (2, '2 Units'), (3, '3 Units'), (4, '4 Units (Standard Subject)'), (5, '5 Units')], default=4),
        ),
        migrations.AlterField(
            model_name='subjectattendancelog',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late / Tardy'), ('CUTTING', 'Cutting Classes'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10),
        ),
    ]
