# Generated by Django 6.0.5 on 2026-10-01 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_classschedule_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGateLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('IN', 'Entry (Arrival)'), ('OUT', 'Exit (Departure)')], max_length=10)),
                ('scan_method', models.CharField(choices=[('RFID', 'RFID Tap (Primary)'), ('QR', 'QR Code Scan (Backup)')], default='RFID', max_length=10)),
                ('raw_identifier', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'student_gate_logs',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='facultygatelog',
            name='idx_faculty_scan_time',
        ),
        migrations.AddField(
            model_name='facultygatelog',
            name='raw_identifier',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultygatelog',
            name='scan_method',
            field=models.CharField(choices=[('RFID', 'RFID Tap (Primary)'), ('QR', 'QR Code Scan (Backup)')], default='RFID', max_length=10),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Backup QR code printed on PVC card', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(blank=True, help_text='Primary RFID card serial number', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='rfid_uid',
            field=models.CharField(blank=True, help_text='Unique RFID card serial number', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_token',
            field=models.CharField(help_text='Backup QR token printed on card', max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['rfid_uid'], name='idx_student_rfid'),
        ),
        migrations.AddField(
            model_name='studentgatelog',
            name='kiosk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.iotkiosk'),
        ),
        migrations.AddField(
            model_name='studentgatelog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_logs', to='academics.student'),
        ),
        migrations.RemoveField(
            model_name='facultygatelog',
            name='card_uid',
        ),
        migrations.AddIndex(
            model_name='studentgatelog',
            index=models.Index(fields=['student', 'scan_time'], name='idx_stu_gate_time'),
        ),
    ]
