# Generated by Django 6.0.5 on 2026-10-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentgatelog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'verbose_name': 'School Profile & Settings', 'verbose_name_plural': 'School Profiles & Settings'},
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='current_academic_year',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='principal',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='geofence_radius_meters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='left_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='right_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='division',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
