# Generated by Django 6.0.5 on 2026-10-04 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_schoolprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=64)),
                ('record_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={},
        ),
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_daily_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gate_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Official School Physical Address'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', help_text='Telephone / Mobile Contact', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='deped_logo',
            field=models.TextField(blank=True, help_text='Official Department of Education Ribbon Emblem', null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Official DepEd Institutional Email', max_length=254),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='kagawaran_logo',
            field=models.TextField(blank=True, help_text='National Seal / Kagawaran ng Edukasyon Logo', null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_logo',
            field=models.TextField(blank=True, help_text='Official School Institutional Crest / Seal', null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgatelog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_student_gate_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='code',
            field=models.CharField(help_text='e.g., 2026-2027', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='first_friday_june',
            field=models.DateField(help_text='Official cut-off date for baseline enrollment statistics'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='label',
            field=models.CharField(default='Regular Faculty Shift', max_length=100),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='late_threshold_min',
            field=models.IntegerField(default=15, help_text='Grace period in minutes'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='regular_days_label',
            field=models.CharField(default='8:00 AM - 12:00 PM and 1:00 PM - 5:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='disability_detail',
            field=models.CharField(blank=True, default='', help_text='Accommodations / Special needs', max_length=150),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the student officially enrolled'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Student'), ('LATE_ENROLLEE', 'Late Enrollee'), ('TRANSFERRED_IN', 'Transferred In'), ('RETURNING', 'Returning Student'), ('REPEATER', 'Repeater / Retained')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_cct_recipient',
            field=models.BooleanField(default=False, help_text='Social aid / Welfare beneficiary'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status_date',
            field=models.DateField(blank=True, help_text='Date status changed (e.g., drop date)', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status_reason_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='transferred_school',
            field=models.CharField(blank=True, default='', help_text='Previous or destination school', max_length=255),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='pass_type',
            field=models.CharField(default='Official Exit Permit', max_length=50),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Valid'), ('USED', 'Used / Checked at Gate'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked / Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='geofencesetting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='geofencesetting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='geofencesetting',
            name='name',
            field=models.CharField(default='Campus Perimeter', max_length=100),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='code',
            field=models.CharField(help_text='e.g., G7, G10, Grade 1', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='level_order',
            field=models.IntegerField(default=1, help_text='Chronological sort order'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='tier',
            field=models.CharField(blank=True, default='Primary', help_text='e.g., Primary, Secondary, High School', max_length=20),
        ),
        migrations.AlterField(
            model_name='iotkiosk',
            name='kiosk_code',
            field=models.CharField(help_text='Unique hardware terminal identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='iotkiosk',
            name='location',
            field=models.CharField(default='Main Gate', help_text='Turnstile or gate position', max_length=100),
        ),
        migrations.AlterField(
            model_name='iotkiosk',
            name='secret_hash',
            field=models.CharField(help_text='Constant-time hardware authentication secret', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='division',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(blank=True, default=250, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='principal_title',
            field=models.CharField(blank=True, default='Principal / School Head', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='e.g., Section A, Diamond, Blue', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='room_number',
            field=models.CharField(blank=True, default='Room 101', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='track_strand',
            field=models.CharField(blank=True, default='', help_text='Optional academic track or program', max_length=150),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'Priority 1 - High (Absence / Emergency)'), (2, 'Priority 2 - Standard (Arrival / Departure)')], default=2),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Transmission'), ('PROCESSING', 'Processing by Gateway'), ('SENT', 'Sent / Delivered'), ('FAILED', 'Failed / Exhausted Retries')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='trigger_event',
            field=models.CharField(choices=[('CLASS_TAP', 'Classroom Attendance Tap'), ('GATE_TAP', 'Gate Kiosk Tap'), ('GATE_PASS', 'Gate Pass Issuance'), ('LOAFING_ALERT', 'Geofence Perimeter Alert'), ('ABSENCE_WARNING', 'Consecutive Absence Alert'), ('BROADCAST', 'School Announcement')], default='CLASS_TAP', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffgatelog',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entry / Arrival'), ('OUT', 'Exit / Departure')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staffgatelog',
            name='scan_method',
            field=models.CharField(choices=[('RFID', 'RFID Card Tap'), ('QR', 'QR Code Scan')], default='RFID', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, default='Faculty', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(help_text='Unique Employee Number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(blank=True, default='Teacher', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Cryptographic QR token', max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='rfid_uid',
            field=models.CharField(blank=True, help_text='RFID card UID', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='barangay',
            field=models.CharField(blank=True, default='', help_text='Neighborhood, Suburb, or Village', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(help_text='Official Date of Birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='', help_text='e.g., Father, Mother, Guardian', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='house_street_sitio',
            field=models.CharField(blank=True, default='', help_text='Street address / House number', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(help_text='Unique Student ID or National Learner Reference Number', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(blank=True, default='', help_text='Primary spoken language', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='municipality_city',
            field=models.CharField(blank=True, default='', help_text='City or Town', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(help_text='Primary parent/guardian mobile number for notifications', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, default='', help_text='Province, State, or County', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_token',
            field=models.CharField(help_text='Salted QR code token generated by database trigger', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentgatelog',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entry / Arrival'), ('OUT', 'Exit / Departure')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentgatelog',
            name='scan_method',
            field=models.CharField(choices=[('RFID', 'RFID Card Tap'), ('QR', 'QR Code Scan')], default='RFID', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='e.g., MATH101, ENG10', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(blank=True, default='Core Curriculum', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='tier',
            field=models.CharField(blank=True, default='Core', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.IntegerField(default=1, help_text='Credits or academic units'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('REGISTRAR', 'Registrar / Academic Staff'), ('TEACHER', 'Teacher / Faculty Adviser'), ('STAFF', 'School Staff')], default='TEACHER', max_length=20),
        ),
        migrations.AlterModelTable(
            name='schoolprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='studentgatelog',
            table='student_gate_logs_partitioned',
        ),
    ]
