# Generated by Django 6.0.5 on 2026-10-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auditlog_alter_schoolprofile_options_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='schoolprofile',
                    table='school_profile',
                ),
            ],
            database_operations=[],
        ),
    ]
