# Generated by Django 6.0.5 on 2026-10-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_schoolprofile_options_alter_student_sex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'verbose_name': 'School Profile', 'verbose_name_plural': 'School Profiles'},
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('TEACHER', 'Faculty / Faculty Adviser')], default='TEACHER', max_length=20),
        ),
    ]
