# Generated by Django 6.0.5 on 2026-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_schoolprofile_options_alter_student_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='bound_device_id',
            field=models.CharField(blank=True, help_text='Unique hardware UUID of the faculty phone.', max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='device_bound_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when paired.', null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='device_model',
            field=models.CharField(blank=True, help_text='Phone model name.', max_length=100, null=True),
        ),
    ]
