# Generated by Django 6.0.5 on 2026-10-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_staffprofile_bound_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Official DepEd School Email', max_length=254),
        ),
    ]