# Generated by Django 6.0.5 on 2026-10-06 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_schoolprofile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='dailyattendancesummary',
            name='idx_daily_sec_date',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='idx_enroll_summary',
        ),
        migrations.RemoveIndex(
            model_name='facultyheartbeat',
            name='idx_heartbeat_time',
        ),
        migrations.RemoveIndex(
            model_name='smsoutbox',
            name='idx_sms_queue_fetch',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_lrn',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_qr',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_student_rfid',
        ),
        migrations.RemoveIndex(
            model_name='studentgatelog',
            name='idx_stu_gate_time',
        ),
        migrations.RemoveIndex(
            model_name='subjectattendancelog',
            name='idx_sub_att_lookup',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='gradelevel',
            name='tier',
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='stage',
            field=models.CharField(blank=True, default='JHS', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='first_friday_june',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='am_arrival_cutoff',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='am_arrival_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='am_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='late_threshold_min',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='pm_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='pm_departure_cutoff',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='regular_days_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyattendancesummary',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('CUTTING', 'Cutting Classes'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='disability_detail',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('LATE_ENROLLEE', 'Late Enrollee'), ('TRANSFERRED_IN', 'Transferred In'), ('RETURNING', 'Returning'), ('REPEATER', 'Repeater')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='is_cct_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='transferred_school',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='facultygatelog',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='bound_device_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='device_bound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculty/'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='qr_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='pass_type',
            field=models.CharField(default='Exit Permit', max_length=50),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='geofencesetting',
            name='name',
            field=models.CharField(default='Campus Boundary', max_length=100),
        ),
        migrations.AlterField(
            model_name='geofencesetting',
            name='radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='level_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='iotkiosk',
            name='kiosk_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='iotkiosk',
            name='location',
            field=models.CharField(default='Main Gate', max_length=100),
        ),
        migrations.AlterField(
            model_name='iotkiosk',
            name='secret_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loafingincident',
            name='status',
            field=models.CharField(default='PENDING_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='deped_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='kagawaran_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='principal_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='track_strand',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='priority',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsoutbox',
            name='trigger_event',
            field=models.CharField(default='CLASS_TAP', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='barangay',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='house_street_sitio',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='lrn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='municipality_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='qr_token',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentgatelog',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(blank=True, default='Core', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subjectattendancelog',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('CUTTING', 'Cutting Classes'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('TEACHER', 'Teacher')], default='TEACHER', max_length=20),
        ),
        migrations.RemoveField(
            model_name='dailyattendancesummary',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='studentgatelog',
            name='recorded_by',
        ),
    ]
