# Generated by Django 6.0.5 on 2026-10-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_schoolprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facultygatelog',
            name='excused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultygatelog',
            name='excused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excused_faculty_gate_violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultygatelog',
            name='is_excused_by_principal',
            field=models.BooleanField(default=False, help_text='Only the School Principal can excuse a loafing violation to prevent salary deduction'),
        ),
        migrations.AddField(
            model_name='facultygatelog',
            name='is_violation',
            field=models.BooleanField(default=False, help_text='Flagged when unauthorized gate exit occurs during official work hours without Gate Pass'),
        ),
        migrations.AddField(
            model_name='facultygatelog',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='facultygatelog',
            name='violation_type',
            field=models.CharField(blank=True, default='', help_text='e.g. LOAFING, PREMATURE_EXIT, CUTTING', max_length=64),
        ),
        migrations.CreateModel(
            name='FacultyMonthlyDTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Month number (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Year (e.g., 2026)')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_dept_head_approved', models.BooleanField(default=False)),
                ('dept_head_approved_at', models.DateTimeField(blank=True, null=True)),
                ('regular_hours', models.CharField(default='8:00 AM - 12:00 PM / 1:00 PM - 5:00 PM', max_length=120)),
                ('saturday_hours', models.CharField(default='As Required', max_length=120)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dtrs', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_dtrs', to='academics.facultyprofile')),
            ],
            options={
                'db_table': 'faculty_monthly_dtr',
                'ordering': ['-year', '-month'],
                'unique_together': {('faculty', 'month', 'year')},
            },
        ),
    ]
