# Generated by Django 6.0.5 on 2026-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_facultygatelog_excused_at_facultygatelog_excused_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('PRINCIPAL', 'School Principal'), ('DEPT_HEAD', 'Department Head'), ('TEACHER', 'Teacher / Adviser'), ('GUARD', 'Security Guard')], default='TEACHER', max_length=20),
        ),
    ]
