# Generated by Django 6.0.5 on 2026-10-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='deped_logo',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='kagawaran_logo',
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='geofence_radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='left_logo',
            field=models.TextField(blank=True, help_text='Left logo for reports (e.g., Ministry, Board, or District seal)', null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='principal_title',
            field=models.CharField(blank=True, default='School Head / Principal', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='right_logo',
            field=models.TextField(blank=True, help_text='Right logo for reports (e.g., Institutional crest or seal)', null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_logo',
            field=models.TextField(blank=True, help_text='Main institutional logo for header and portal navigation', null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(blank=True, default='Institutional Portal', max_length=255),
        ),
    ]
