# Generated by Django 6.0.5 on 2026-10-09 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_schoolprofile_deped_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'verbose_name': 'School Profile', 'verbose_name_plural': 'School Profile'},
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='principal_faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty member serving as School Head / Principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_as_principal', to='academics.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='geofence_radius_meters',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='latitude',
            field=models.FloatField(default=8.4858),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='left_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='longitude',
            field=models.FloatField(default=124.6567),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='principal_title',
            field=models.CharField(blank=True, default='Secondary School Principal IV', max_length=150),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='right_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='schoolprofile',
            table='attendsure_school_profile',
        ),
    ]
